### ISSUE TITLE
lib folder is empty in v3.5 release

### ISSUE THREAD

**Issue by DeoLeung** [pgq/pgqd#2]
maybe add it back or notice users to download it

**Comment by jflambert** [comment]
Thank you for the heads up. I was trying to build from source myself. Here's what made it work for me on ubuntu 18.04

```
sudo apt install autoconf python3-docutils libevent-dev
git clone https://github.com/pgq/pgqd.git
cd pgqd && rm -rf lib
git clone https://github.com/libusual/libusual.git lib
./autogen.sh
./configure --prefix=/opt
make
make install
```

**Comment by wuputah** [comment]
Looks like it's a submodule, so I believe you want to do `git submodule update --init`
https://github.com/pgq/pgqd/blob/master/.gitmodules

**Comment by markokr** [comment]
Official tarball - pgqd-3.5.tar.gz - is fine, the problem is with Github generated repo archives - "Source code tgz/zip".

Nothing I can do about that.
