### ISSUE TITLE
Multiple database list

### ISSUE THREAD

**Issue by PeterEgorov** [pgq/pgqd#4]
Previously I used the skytools version 3.2.6.
I had replication from one central server to several nodes. And also replication from all nodes to one central server.
For this I used 2 pgqd.
The configuration file (pgqd_center.conf and pgqd_nodes.conf) looked like this:

pgqd_center.conf:
[pgqd]
base_connstr = dbname=centralnode host=192.168.1.10 port=5432 user=postgres

pgqd_nodes.conf:
[pgqd]
database_list = simplenode dbname=simplenode host=192.168.1.1 port=5432 user=postgres, simplenode dbname=simplenode host=192.168.1.2 port=5432 user=postgres, simplenode dbname=simplenode host=192.168.1.3 port=5432 user=postgres

everything worked well.

But when I needed to use new versions of londiste, pgq, pgqd-3.5, these configuration files do not work.
I'm getting errors:
WARNING [simplenode dbname=simplenode host=192.168.1.1 port=5432 user=postgres]: default timeout
LOG {ticks: 0, maint: 0, retry: 0}
LOG {ticks: 0, maint: 0, retry: 0}
ERROR connection error: PQconnectPoll
ERROR libpq: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  database "simplenode dbname=simplenode host=192.168.1.1 port=5432 user=po" does not exist 

How in the new version of pgqd it is necessary to specify a list of several databases located on different hosts?

**Comment by markokr** [comment]
It is not a supported configuration, seems it worked only by accident.

It is better to run pgqd per host and locally, not over network, that way any network outages will not affect batch generation in local pgq.  If pgqd goes down, it is not possible to spread events into batches that where inserted during outage.

IOW - please run local pgqd instead trying to get your old configuration to work.

**Comment by markokr** [comment]
Closing.
